"""phase 2 data intelligence pipeline

Revision ID: 081a88d02574
Revises: e308a313166d
Create Date: 2026-08-28 19:11:25.450185
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '081a88d02574'
down_revision: str | None = 'e308a313166d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=True)
    op.create_table('entities',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('canonical_value', sa.String(length=512), nullable=False),
    sa.Column('blocking_key', sa.String(length=64), nullable=False),
    sa.Column('display_value', sa.String(length=512), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('person', 'phone', 'vehicle', 'organization', 'account', 'location', 'document', 'event')", name=op.f('ck_entities_entity_type_valid')),
    sa.CheckConstraint("status IN ('active', 'merged', 'review', 'rejected')", name=op.f('ck_entities_entity_status_valid')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_entities_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('case_id', 'entity_type', 'canonical_value', name='uq_entities_case_type_value')
    )
    op.create_index(op.f('ix_entities_blocking_key'), 'entities', ['blocking_key'], unique=False)
    op.create_index(op.f('ix_entities_case_id'), 'entities', ['case_id'], unique=False)
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_table('evidence_files',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=True),
    sa.Column('encoding', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('stored', 'parsed', 'processing', 'failed')", name=op.f('ck_evidence_files_evidence_file_status_valid')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_evidence_files_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], name=op.f('fk_evidence_files_data_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_files')),
    sa.UniqueConstraint('case_id', 'sha256', name='uq_evidence_files_case_sha256')
    )
    op.create_index(op.f('ix_evidence_files_case_id'), 'evidence_files', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_files_data_source_id'), 'evidence_files', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_evidence_files_format'), 'evidence_files', ['format'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_file_id', sa.Uuid(), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('processed_records', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('graph_sync_status', sa.String(length=32), nullable=False),
    sa.Column('graph_error', sa.Text(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("graph_sync_status IN ('pending', 'synced', 'failed')", name=op.f('ck_ingestion_jobs_ingestion_job_graph_sync_valid')),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'partial')", name=op.f('ck_ingestion_jobs_ingestion_job_status_valid')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_ingestion_jobs_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_file_id'], ['evidence_files.id'], name=op.f('fk_ingestion_jobs_evidence_file_id_evidence_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_jobs'))
    )
    op.create_index(op.f('ix_ingestion_jobs_case_id'), 'ingestion_jobs', ['case_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_evidence_file_id'), 'ingestion_jobs', ['evidence_file_id'], unique=False)
    op.create_table('source_records',
    sa.Column('evidence_file_id', sa.Uuid(), nullable=False),
    sa.Column('record_no', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entity_mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relationships_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('parsed', 'normalized', 'extracted', 'resolved', 'failed')", name=op.f('ck_source_records_source_record_status_valid')),
    sa.ForeignKeyConstraint(['evidence_file_id'], ['evidence_files.id'], name=op.f('fk_source_records_evidence_file_id_evidence_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_records')),
    sa.UniqueConstraint('evidence_file_id', 'record_no', name='uq_source_records_file_record')
    )
    op.create_index(op.f('ix_source_records_evidence_file_id'), 'source_records', ['evidence_file_id'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('source_record_id', sa.Uuid(), nullable=True),
    sa.Column('alias_value', sa.String(length=512), nullable=False),
    sa.Column('alias_type', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_aliases_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_entity_aliases_source_record_id_source_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_aliases')),
    sa.UniqueConstraint('entity_id', 'alias_value', name='uq_entity_aliases_entity_value')
    )
    op.create_index(op.f('ix_entity_aliases_entity_id'), 'entity_aliases', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_aliases_source_record_id'), 'entity_aliases', ['source_record_id'], unique=False)
    op.create_table('entity_candidates',
    sa.Column('source_record_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('raw_value', sa.String(length=512), nullable=False),
    sa.Column('normalized_value', sa.String(length=512), nullable=False),
    sa.Column('blocking_key', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('resolution_status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("resolution_status IN ('pending', 'auto_match', 'review', 'no_match')", name=op.f('ck_entity_candidates_entity_candidate_resolution_valid')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_candidates_entity_id_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_entity_candidates_source_record_id_source_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_candidates')),
    sa.UniqueConstraint('source_record_id', 'entity_type', 'normalized_value', name='uq_entity_candidates_record_type_value')
    )
    op.create_index(op.f('ix_entity_candidates_blocking_key'), 'entity_candidates', ['blocking_key'], unique=False)
    op.create_index(op.f('ix_entity_candidates_entity_id'), 'entity_candidates', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_candidates_entity_type'), 'entity_candidates', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_candidates_source_record_id'), 'entity_candidates', ['source_record_id'], unique=False)
    op.create_table('relationships',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_record_id', sa.Uuid(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("relationship_type IN ('called', 'owns', 'works_for', 'associated_with', 'located_at', 'visited', 'transferred_to')", name=op.f('ck_relationships_relationship_type_valid')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_relationships_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name=op.f('fk_relationships_source_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_relationships_source_record_id_source_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('fk_relationships_target_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships')),
    sa.UniqueConstraint('case_id', 'source_entity_id', 'target_entity_id', 'relationship_type', 'source_record_id', name='uq_relationships_case_src_dst_type_record')
    )
    op.create_index(op.f('ix_relationships_case_id'), 'relationships', ['case_id'], unique=False)
    op.create_index(op.f('ix_relationships_relationship_type'), 'relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_relationships_source_entity_id'), 'relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_source_record_id'), 'relationships', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_entity_id'), 'relationships', ['target_entity_id'], unique=False)
    op.create_table('entity_matches',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('source_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('auto_match', 'review', 'no_match')", name=op.f('ck_entity_matches_entity_match_decision_valid')),
    sa.CheckConstraint("status IN ('active', 'merged', 'review', 'rejected')", name=op.f('ck_entity_matches_entity_match_status_valid')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_entity_matches_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_candidate_id'], ['entity_candidates.id'], name=op.f('fk_entity_matches_source_candidate_id_entity_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('fk_entity_matches_target_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_matches'))
    )
    op.create_index(op.f('ix_entity_matches_case_id'), 'entity_matches', ['case_id'], unique=False)
    op.create_index(op.f('ix_entity_matches_source_candidate_id'), 'entity_matches', ['source_candidate_id'], unique=False)
    op.create_index(op.f('ix_entity_matches_target_entity_id'), 'entity_matches', ['target_entity_id'], unique=False)
    op.create_table('relationship_evidence',
    sa.Column('relationship_id', sa.Uuid(), nullable=False),
    sa.Column('source_record_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], name=op.f('fk_relationship_evidence_relationship_id_relationships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_relationship_evidence_source_record_id_source_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship_evidence')),
    sa.UniqueConstraint('relationship_id', 'source_record_id', 'evidence_type', name='uq_relationship_evidence_rel_record_type')
    )
    op.create_index(op.f('ix_relationship_evidence_relationship_id'), 'relationship_evidence', ['relationship_id'], unique=False)
    op.create_index(op.f('ix_relationship_evidence_source_record_id'), 'relationship_evidence', ['source_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationship_evidence_source_record_id'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_relationship_evidence_relationship_id'), table_name='relationship_evidence')
    op.drop_table('relationship_evidence')
    op.drop_index(op.f('ix_entity_matches_target_entity_id'), table_name='entity_matches')
    op.drop_index(op.f('ix_entity_matches_source_candidate_id'), table_name='entity_matches')
    op.drop_index(op.f('ix_entity_matches_case_id'), table_name='entity_matches')
    op.drop_table('entity_matches')
    op.drop_index(op.f('ix_relationships_target_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_record_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_relationship_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_case_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_entity_candidates_source_record_id'), table_name='entity_candidates')
    op.drop_index(op.f('ix_entity_candidates_entity_type'), table_name='entity_candidates')
    op.drop_index(op.f('ix_entity_candidates_entity_id'), table_name='entity_candidates')
    op.drop_index(op.f('ix_entity_candidates_blocking_key'), table_name='entity_candidates')
    op.drop_table('entity_candidates')
    op.drop_index(op.f('ix_entity_aliases_source_record_id'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_entity_id'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_source_records_evidence_file_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_ingestion_jobs_evidence_file_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_case_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_evidence_files_format'), table_name='evidence_files')
    op.drop_index(op.f('ix_evidence_files_data_source_id'), table_name='evidence_files')
    op.drop_index(op.f('ix_evidence_files_case_id'), table_name='evidence_files')
    op.drop_table('evidence_files')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_case_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_blocking_key'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###