"""add collections, field devices, hypotheses, timeline, reports

Revision ID: 6050ea12acad
Revises: w2b3c4d5e6f7
Create Date: 2026-09-10 18:04:02.611433
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '6050ea12acad'
down_revision: str | None = 'w2b3c4d5e6f7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'open', 'sealed')", name=op.f('ck_collections_collection_status_valid')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_collections_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_collections_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    op.create_index(op.f('ix_collections_case_id'), 'collections', ['case_id'], unique=False)
    op.create_index(op.f('ix_collections_owner_id'), 'collections', ['owner_id'], unique=False)
    op.create_table('field_devices',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('serial', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('signature_algorithm', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('android_mobile', 'esp32', 'raspberry_pi', 'tablet', 'laptop', 'other')", name=op.f('ck_field_devices_field_device_platform_valid')),
    sa.CheckConstraint("signature_algorithm IN ('RSA-SHA256', 'Ed25519')", name=op.f('ck_field_devices_field_device_signature_algorithm_valid')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'revoked', 'suspended')", name=op.f('ck_field_devices_field_device_status_valid')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_field_devices_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_field_devices_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_field_devices_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_devices')),
    sa.UniqueConstraint('case_id', 'serial', name='uq_field_devices_case_serial')
    )
    op.create_index(op.f('ix_field_devices_case_id'), 'field_devices', ['case_id'], unique=False)
    op.create_index(op.f('ix_field_devices_user_id'), 'field_devices', ['user_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contradicting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_relationships', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_weight', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('fact', 'observation', 'inference', 'hypothesis')", name=op.f('ck_hypotheses_hypothesis_kind_valid')),
    sa.CheckConstraint("status IN ('proposed', 'under_review', 'supported', 'contradicted', 'dismissed', 'concluded')", name=op.f('ck_hypotheses_hypothesis_status_valid')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_hypotheses_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_hypotheses_submitted_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypotheses'))
    )
    op.create_index(op.f('ix_hypotheses_case_id'), 'hypotheses', ['case_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_submitted_by'), 'hypotheses', ['submitted_by'], unique=False)
    op.create_table('reports',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('minio_key', sa.String(length=512), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("format IN ('json', 'csv', 'pdf')", name=op.f('ck_reports_report_format_valid')),
    sa.CheckConstraint("report_type IN ('case_summary', 'intelligence', 'evidence_manifest', 'timeline', 'network_analysis')", name=op.f('ck_reports_report_type_valid')),
    sa.CheckConstraint("status IN ('generating', 'ready', 'failed')", name=op.f('ck_reports_report_status_valid')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_reports_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reports_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_reports_created_by'), 'reports', ['created_by'], unique=False)
    op.create_table('timeline_events',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_file_id', sa.Uuid(), nullable=True),
    sa.Column('collection_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('evidence_uploaded', 'evidence_restored', 'collection_created', 'collection_sealed', 'package_imported', 'device_registered', 'device_approved', 'device_revoked', 'analytics_run', 'finding_created', 'entity_merged', 'match_accepted', 'match_rejected', 'hypothesis_created', 'hypothesis_status_changed', 'report_generated', 'case_event', 'iot_event')", name=op.f('ck_timeline_events_timeline_event_kind_valid')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_timeline_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_timeline_events_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_timeline_events_collection_id_collections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['field_devices.id'], name=op.f('fk_timeline_events_device_id_field_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_timeline_events_entity_id_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_file_id'], ['evidence_files.id'], name=op.f('fk_timeline_events_evidence_file_id_evidence_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    op.create_index(op.f('ix_timeline_events_actor_user_id'), 'timeline_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_case_id'), 'timeline_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_collection_id'), 'timeline_events', ['collection_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_device_id'), 'timeline_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_entity_id'), 'timeline_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_evidence_file_id'), 'timeline_events', ['evidence_file_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_kind'), 'timeline_events', ['kind'], unique=False)
    op.create_index(op.f('ix_timeline_events_occurred_at'), 'timeline_events', ['occurred_at'], unique=False)
    op.add_column('entities', sa.Column('merged_into_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_entities_merged_into_id'), 'entities', ['merged_into_id'], unique=False)
    op.create_foreign_key(op.f('fk_entities_merged_into_id_entities'), 'entities', 'entities', ['merged_into_id'], ['id'], ondelete='SET NULL')
    op.add_column('evidence_files', sa.Column('collection_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_evidence_files_collection_id'), 'evidence_files', ['collection_id'], unique=False)
    op.create_foreign_key(op.f('fk_evidence_files_collection_id_collections'), 'evidence_files', 'collections', ['collection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_evidence_files_collection_id_collections'), 'evidence_files', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_files_collection_id'), table_name='evidence_files')
    op.drop_column('evidence_files', 'collection_id')
    op.drop_constraint(op.f('fk_entities_merged_into_id_entities'), 'entities', type_='foreignkey')
    op.drop_index(op.f('ix_entities_merged_into_id'), table_name='entities')
    op.drop_column('entities', 'merged_into_id')
    op.drop_index(op.f('ix_timeline_events_occurred_at'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_kind'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_evidence_file_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_entity_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_device_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_collection_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_case_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_actor_user_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_reports_created_by'), table_name='reports')
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_hypotheses_submitted_by'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_case_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_field_devices_user_id'), table_name='field_devices')
    op.drop_index(op.f('ix_field_devices_case_id'), table_name='field_devices')
    op.drop_table('field_devices')
    op.drop_index(op.f('ix_collections_owner_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_case_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###