"""add evidence source field device provenance

Revision ID: 6b4a8da27811
Revises: 6050ea12acad
Create Date: 2026-09-12 23:16:07.230774
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6b4a8da27811'
down_revision: str | None = '6050ea12acad'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_files', sa.Column('source_field_device_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_evidence_files_source_field_device_id'), 'evidence_files', ['source_field_device_id'], unique=False)
    op.create_foreign_key(op.f('fk_evidence_files_source_field_device_id_field_devices'), 'evidence_files', 'field_devices', ['source_field_device_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_evidence_files_source_field_device_id_field_devices'), 'evidence_files', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_files_source_field_device_id'), table_name='evidence_files')
    op.drop_column('evidence_files', 'source_field_device_id')
    # ### end Alembic commands ###