"""Stable machine-readable API error codes (single source of truth).

These constants live outside any API package so both the service layer (which
signals domain conditions) and the API layer (which maps them to HTTP
responses) can reference them without a circular import through the ``app.api``
package tree.
"""

from __future__ import annotations

# Authentication / account lifecycle.
CODE_INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
CODE_ACCOUNT_PENDING = "ACCOUNT_PENDING"
CODE_ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED"
CODE_ACCOUNT_REJECTED = "ACCOUNT_REJECTED"
CODE_ACCOUNT_TRANSITION_INVALID = "ACCOUNT_TRANSITION_INVALID"
CODE_ACCOUNT_NOT_ACTIVE = "ACCOUNT_NOT_ACTIVE"

# Authorization / access control.
CODE_INSUFFICIENT_PERMISSION = "INSUFFICIENT_PERMISSION"
CODE_CASE_ACCESS_DENIED = "CASE_ACCESS_DENIED"
CODE_CASE_READ_ONLY = "CASE_READ_ONLY"

# Registration.
CODE_DUPLICATE_EMAIL = "DUPLICATE_EMAIL"

# IoT.
CODE_DUPLICATE_DEVICE_SERIAL = "DUPLICATE_DEVICE_SERIAL"

# Entity resolution review.
CODE_MATCH_NOT_REVIEW = "MATCH_NOT_REVIEW"
CODE_MATCH_NO_TARGET = "MATCH_NO_TARGET"
CODE_MERGE_SAME_ENTITY = "MERGE_SAME_ENTITY"
CODE_PRIMARY_NOT_FOUND = "PRIMARY_NOT_FOUND"
CODE_MERGE_NOT_FOUND = "MERGE_NOT_FOUND"
CODE_PRIMARY_IS_MERGED = "PRIMARY_IS_MERGED"
CODE_TYPE_MISMATCH = "TYPE_MISMATCH"

# Device registration / verification.
CODE_DEVICE_NOT_FOUND = "DEVICE_NOT_FOUND"
CODE_DEVICE_REVOKED = "DEVICE_REVOKED"
CODE_DEVICE_UNAPPROVED = "DEVICE_UNAPPROVED"
CODE_SIGNATURE_INVALID = "SIGNATURE_INVALID"
CODE_HASH_MISMATCH = "HASH_MISMATCH"
CODE_REPLAY = "REPLAY_DETECTED"
CODE_MANIFEST_INVALID = "MANIFEST_INVALID"
CODE_DUPLICATE_FILENAME_IN_MANIFEST = "DUPLICATE_FILENAME_IN_MANIFEST"

# Hypothesis lifecycle.
CODE_HYPOTHESIS_NOT_FOUND = "HYPOTHESIS_NOT_FOUND"
CODE_HYPOTHESIS_INVALID_TRANSITION = "HYPOTHESIS_INVALID_TRANSITION"

MESSAGES = {
    CODE_INVALID_CREDENTIALS: "invalid username or password",
    CODE_ACCOUNT_PENDING: "account is pending administrator approval",
    CODE_ACCOUNT_SUSPENDED: "account has been suspended",
    CODE_ACCOUNT_REJECTED: "account registration was rejected",
}
